### ISSUE TITLE
Artist search - exception raised when Name field blank

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2338]
If the Name field is blank, the artist search URL tries to list it in the URL anyway (`search[name]=&search[order]=created_at`), causing an exception:
````
ActionController::ActionControllerError exception raised

    Cannot redirect to a parameter hash!
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/redirecting.rb:67:in `redirect_to'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/flash.rb:57:in `redirect_to'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:61:in `block in redirect_to'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:60:in `redirect_to'
    /var/www/danbooru2/releases/20150124214131/app/controllers/application_controller.rb:118:in `normalize_search'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `call'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:160:in `block in halting'
    /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
[...]
````

**Comment by Staghelm** [comment]
Being new at this thing, I have no clue how to add this so I too can prevent having the "cannot redirect to a parameter hash!"

**Comment by ToksT** [comment]
> Being new at this thing, I have no clue how to add this so I too can prevent having the "cannot redirect to a parameter hash!"

It should already be fixed.
