### ISSUE TITLE
Stuck and I have no idea where

### ISSUE THREAD

**Issue by tranquilitycal** [r888888888/danbooru#2355]
When I tried to run unicorn_rails it didn't exactly work and then if I try to run rails console I get this error

```
danbooru@hexbug:~/danbooru$ rails console
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:247:in `require': cannot load such file -- /home/danbooru/danbooru/config/danbooru_local_config (LoadError)
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:247:in `block in require'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:247:in `require'
	from /home/danbooru/danbooru/config/initializers/danbooru_config.rb:2:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:241:in `load'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:241:in `block in load'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:241:in `load'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:648:in `block in load_config_initializer'
	from /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:161:in `instrument'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:647:in `load_config_initializer'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:611:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/engine.rb:611:in `block in <class:Engine>'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
	from /usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
	from /usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
	from /usr/lib/ruby/vendor_ruby/rails/application.rb:300:in `initialize!'
	from /home/danbooru/danbooru/config/environment.rb:5:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:247:in `require'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:247:in `block in require'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:232:in `load_dependency'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:247:in `require'
	from /usr/lib/ruby/vendor_ruby/rails/application.rb:276:in `require_environment!'
	from /usr/lib/ruby/vendor_ruby/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
	from /usr/lib/ruby/vendor_ruby/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/lib/ruby/vendor_ruby/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /usr/lib/ruby/vendor_ruby/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>' ```


Any help?

**Comment by r888888888** [comment]
You can download this file:

https://github.com/r888888888/danbooru/blob/master/script/install/danbooru_local_config.rb.templ

Into the config directory. Be sure to rename it.

**Comment by tranquilitycal** [comment]
Thank you that did fix the issue. I got it working now 
:+1:
