### ISSUE TITLE
"Random post" causes RecordNotFound exceptions

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2415]
Go to http://danbooru.donmai.us/posts/random?tags=touhou+rating%3As+solo , then press R repeatedly to go to random post. Somehow, about 50% of time I run into this:

```
ActiveRecord::RecordNotFound exception raised
ActiveRecord::RecordNotFound
/var/www/danbooru2/releases/20150618193303/app/controllers/posts_controller.rb:103:in `random'
...
```

Additionally, on larger sets like just touhou, I often run into statement timeouts when getting random post. I wonder if the actual select + offset statement causes those, or count statement, or something else entirely?

**Comment by ToksT** [comment]
`Post.fast_count` is timing out and returning 1 million for that search. You can check it [here](http://danbooru.donmai.us/counts/posts.json?tags=touhou+rating%3As+solo). Because it's giving 1 million despite the search only having about 220,000 posts, if the random selects a post between 220,001 and 1,000,000 then it will error out because there is no such post in the query.

The reason it's timing out is because Albert changed Post.fast_count to only have a 500ms timeout if your query has any metatags in it (see 709943b627e3d935d12d7b15634b77a7114a7381). Normally it would use the user's statement timeout (e.g. 9 seconds).

@r888888888 Why is this?

**Comment by ToksT** [comment]
> Additionally, on larger sets like just touhou, I often run into statement timeouts when getting random post. I wonder if the actual select + offset statement causes those, or count statement, or something else entirely?

That's simpler: it's the select + offset part, the part that actually gets the post. You'll notice the same thing happens on occasion in a non-random query if you try to use a huge offset like [this](http://danbooru.donmai.us/posts?tags=touhou&page=2500&limit=200) (200 posts per page * 2500 pages = 500,000 offset). There's probably nothing we can do about this.

**Comment by Type-kun** [comment]
> if you try to use a huge offset like this (200 posts per page * 2500 pages = 500,000 offset).

Touhou doesn't have 500 000 posts, though :3 But I see what you mean with 2000 pages. 

Hmm. There's some dirty hack I encountered on stackoverflow, suggesting to only select the ID using offset, to reduce the amount of data being sorted, and then fetch the record by that ID. I wonder if that would yield any real benefits, but seems worth trying from theoretical standpoint at least.

**Comment by Type-kun** [comment]
On a second thought, perhaps it would be better to query the ID directly without ANY ordering. This might actually speed up things. It seems worth trying it out first; if it actually works, "order:none" should be introduced to remove any ordering from the query.

**Comment by ToksT** [comment]
> On a second thought, perhaps it would be better to query the ID directly without ANY ordering. This might actually speed up things. It seems worth trying it out first; if it actually works, "order:none" should be introduced to remove any ordering from the query.

That makes a lot of sense. It does seem to improve performance quite a bit:

```sql
SELECT "posts".* FROM "posts" WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru', E'(''touhou'')')) ORDER BY posts.id DESC LIMIT 1 OFFSET 100000

"Limit  (cost=244574.78..244577.23 rows=1 width=1050)"
"  ->  Index Scan Backward using posts_pkey on posts  (cost=0.43..880859.43 rows=360160 width=1050)"
"        Filter: (tag_index @@ '''touhou'''::tsquery)"
```
```sql
SELECT "posts".* FROM "posts" WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru', E'(''touhou'')')) LIMIT 1 OFFSET 100000

"Limit  (cost=63356.98..63357.61 rows=1 width=1050)"
"  ->  Seq Scan on posts  (cost=0.00..228186.50 rows=360160 width=1050)"
"        Filter: (tag_index @@ '''touhou'''::tsquery)"
```

**Comment by Type-kun** [comment]
Oh, so DB knowledge from my work finally pays off :3

Moving on - does it help if only post ID is selected? It might reduce `width` parameter and influence overall cost, though I'm not sure about that.

Also, same thing should be done for `order:random`, probably.

**Comment by ToksT** [comment]
> Moving on - does it help if only post ID is selected? It might reduce width parameter and influence overall cost, though I'm not sure about that.

Selecting only id reduces width from 1050 -> 4, but cost is not affected at all. This is true both before and after I removed the `ORDER BY posts.id DESC` part.

> Also, same thing should be done for order:random, probably.

order:random already has no order, as suggested by Albert [here](https://github.com/r888888888/danbooru/issues/1938#issuecomment-103972037).

**Comment by Type-kun** [comment]
> Selecting only id reduces width from 1050 -> 4, but cost is not affected at all. This is true both before and after I removed the  ORDER BY posts.id DESC  part.

Well then, we'll have to settle with the speedup from removing the ordering, 4x seems nice enough.

**Comment by ToksT** [comment]
Back to the original topic:

> Post.fast_count is timing out and returning 1 million for that search.

This should be fixed as of 6ad6aa44c4bff11c6f41be47bad653122920880d. Metatags no longer have a short 500ms timeout when getting the count.

**Comment by Type-kun** [comment]
It will begin again if slow_query is amended again, though.

**Comment by r888888888** [comment]
I didn't realize I took out the shortened statement timeout. That could be a problem, those counts are expensive and can easily clog up the database.

**Comment by ToksT** [comment]
> I didn't realize I took out the shortened statement timeout. That could be a problem, those counts are expensive and can easily clog up the database.

Is it expensive for every metatag? Only shortening it for the expensive ones and allowing other metatags to have the normal timeout would be ideal.

**Comment by kittey** [comment]
I just got this exception again while skipping through random posts. I didn't search for anything, so it was selecting random posts from everything Danbooru has: `http://danbooru.donmai.us/posts/random`
```
ActiveRecord::RecordNotFound exception raised

    ActiveRecord::RecordNotFound
    app/controllers/posts_controller.rb:97:in `random'
```

**Comment by evazion** [comment]
```ruby
# https://github.com/r888888888/danbooru/blob/master/app/controllers/posts_controller.rb#L95
count = Post.fast_count(params[:tags], :statement_timeout => CurrentUser.user.statement_timeout)
@post = Post.tag_match(params[:tags]).reorder("").offset(rand(count)).first
raise ActiveRecord::RecordNotFound if @post.nil?
```

I guess if Post.fast_count returns an over-estimated count, then it could offset past the end and return nil. But over-estimating the count for a blank tag search should never happen...

**Comment by evazion** [comment]
> Hmm. There's some dirty hack I encountered on stackoverflow, suggesting to only select the ID using offset, to reduce the amount of data being sorted, and then fetch the record by that ID. I wonder if that would yield any real benefits, but seems worth trying from theoretical standpoint at least.

I tested this, it is somewhat faster because it's able to do an index only scan rather than a seq scan in this situation. But not by a whole lot, only 200ms.

https://explain.depesz.com/s/ZnP
https://explain.depesz.com/s/e3q

**Comment by evazion** [comment]
I tried an alternate method: instead of picking a random offset, pick a random md5 and find the post closest to it:

```ruby
Post Load (2.0ms)  SELECT  "posts".* FROM "posts" WHERE (true) AND (md5 <= 'f28a8e26fec7ecbed3c960f9c96e85d7')  ORDER BY md5 desc LIMIT 1
```

This is much faster for the simple case of no tags. The only problem is with some tag searches it completely falls apart: 

/posts/random?tags=kurisu_takaya: md5 index scan, 4800ms: https://explain.depesz.com/s/E2qC
/posts/random?tags=kurisu_takaya: tag_index bitmap scan, 0.078ms: https://explain.depesz.com/s/z06L

Postgres estimates that `kurisu_takaya md5:<ff06652070c7e3d11ecb64390a84cbf1` matches 6900 posts so it chooses the md5 index, when in reality it only has 2 posts so using the tag_index would be better.

**Comment by r888888888** [comment]
That's cute. Would probably still need at least two queries in case there's nothing less than the random md5. It seems extremely fast for me but because md5 has such a high cardinality it's probably sensitive to the statistics setting (see https://www.postgresql.org/docs/9.5/static/planner-stats.html) and server configuration.

**Comment by evazion** [comment]
> That's cute. Would probably still need at least two queries in case there's nothing less than the random md5. 

Yeah, the actual code I tried is this: https://gist.github.com/evazion/4898ebde49743b9a16945adb35eb4278.

> It seems extremely fast for me but because md5 has such a high cardinality it's probably sensitive to the statistics setting (see https://www.postgresql.org/docs/9.5/static/planner-stats.html) and server configuration.

How is the production server configured? I'm using `shared_buffers = 8GB`, `effective_cache_size = 10GB`, `random_page_cost = 1`, and `pg_prewarm` to force everything into memory. This is on a VM with 12GB of RAM and a SSD. I experimented a little with raising the statistics target a while back, but wasn't sure what a good value would be.

**Comment by r888888888** [comment]
Default statistics target is set to 1000.

The only downside with this method for the listing is issuing 20+ queries for a single page. I think this is still better than what we have currently though so I will switch to it.
