### ISSUE TITLE
Attempt to delete an artist creates error "PG::UndefinedColumn exception raised"

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2483]
PG::UndefinedColumn exception raised
ERROR: column "version" does not exist LINE 1: SELECT MAX(version) AS max_id FROM "artist_versions" WHERE ... ^
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:869:in `prepare'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:869:in `prepare_statement'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:826:in `exec_cache'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `exec_query'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:954:in `select'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in `cache_sql'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/calculations.rb:265:in `execute_simple_calculation'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/calculations.rb:119:in `calculate'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/calculations.rb:66:in `maximum'
/var/www/danbooru2/releases/20150808003008/app/models/artist.rb:149:in `merge_version'
/var/www/danbooru2/releases/20150808003008/app/models/artist.rb:119:in `create_version'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:221:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/persistence.rb:221:in `update_attribute'
/var/www/danbooru2/releases/20150808003008/app/controllers/artists_controller.rb:91:in `destroy'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:189:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:113:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:229:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:166:in `block in halting'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `block in instrument'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:159:in `instrument'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/abstract_controller/base.rb:136:in `process'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionview-4.1.8/lib/action_view/rendering.rb:30:in `process'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal.rb:196:in `dispatch'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_controller/metal.rb:232:in `block in action'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:50:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:73:in `block in call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `each'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/journey/router.rb:59:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/routing/route_set.rb:678:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/flash.rb:254:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/query_cache.rb:36:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:82:in `run_callbacks'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:38:in `call_app'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `block in call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/rack/logger.rb:20:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/actionpack-4.1.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/engine.rb:514:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/railties-4.1.8/lib/rails/application.rb:144:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:572:in `process_client'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/gctools-0.2.3/lib/gctools/oobgc/unicorn_middleware.rb:13:in `process_client'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:666:in `worker_loop'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:521:in `spawn_missing_workers'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/lib/unicorn/http_server.rb:140:in `start'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.8.2/bin/unicorn:126:in `<top (required)>'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'

**Comment by Kikimaru** [comment]
Please see my comment on Danbooru comment
forum #107320 
for code
