### ISSUE TITLE
dependencies.rb:457:in `load': No such file to load -- gctools/oobgc

### ISSUE THREAD

**Issue by cglmrfreeman** [r888888888/danbooru#2605]
Greetings again.

I asked for support in my previous issue because I thought I could get it there, but apparently not. Perhaps it was because I did not follow the directions exactly. Well I wiped my server and this time I did with ruby version 2.1.5 and `rbenv` in it's proper location this time. I did not alter anything the `INSTALL.debian` script. Here is the error I am getting now (again).
```
I, [2016-05-31T12:41:57.427189 #23312]  INFO -- : inherited addr=127.0.0.1:9000 fd=12
I, [2016-05-31T12:41:57.428631 #23312]  INFO -- : worker=0 spawning...
I, [2016-05-31T12:41:57.435134 #23312]  INFO -- : worker=1 spawning...
I, [2016-05-31T12:41:57.441040 #23312]  INFO -- : master process ready
I, [2016-05-31T12:41:57.444476 #23316]  INFO -- : worker=0 spawned pid=23316
I, [2016-05-31T12:41:57.455221 #23319]  INFO -- : worker=1 spawned pid=23319
I, [2016-05-31T12:41:57.534391 #23316]  INFO -- : Refreshing Gem list
I, [2016-05-31T12:41:57.536520 #23319]  INFO -- : Refreshing Gem list
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:457:in `load': No such file to load -- gctools/oobgc (LoadError)
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:457:in `block in load_file'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:456:in `load_file'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:354:in `require_or_load'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:317:in `depend_on'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:233:in `require_dependency'
        from config.ru:7:in `block in <main>'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:632:in `init_worker_process'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:655:in `worker_loop'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
/var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:457:in `load': No such file to load -- gctools/oobgc (LoadError)
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:457:in `block in load_file'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:456:in `load_file'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:354:in `require_or_load'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:317:in `depend_on'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:233:in `require_dependency'
        from config.ru:7:in `block in <main>'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:632:in `init_worker_process'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:655:in `worker_loop'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `load'
        from /var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn:23:in `<main>'
E, [2016-05-31T12:42:27.865628 #23312] ERROR -- : reaped #<Process::Status: pid 23316 exit 1> worker=0
E, [2016-05-31T12:42:27.868061 #23312] ERROR -- : reaped #<Process::Status: pid 23319 exit 1> worker=1
I, [2016-05-31T12:42:27.871401 #23312]  INFO -- : master complete
I, [2016-05-31T12:43:07.234314 #22548]  INFO -- : done reloading config_file=/var/www/danbooru2/current/config/unicorn/development.rb
E, [2016-05-31T12:43:10.814463 #22548] ERROR -- : reaped #<Process::Status: pid 23451 exit 1> worker=0
E, [2016-05-31T12:43:10.815762 #22548] ERROR -- : reaped #<Process::Status: pid 23453 exit 1> worker=1
I, [2016-05-31T12:43:10.817443 #22548]  INFO -- : worker=0 spawning...
I, [2016-05-31T12:43:10.819014 #22548]  INFO -- : worker=1 spawning...
I, [2016-05-31T12:43:10.839096 #23533]  INFO -- : worker=0 spawned pid=23533
I, [2016-05-31T12:43:10.839658 #23535]  INFO -- : worker=1 spawned pid=23535
I, [2016-05-31T12:43:10.854209 #23535]  INFO -- : Refreshing Gem list
I, [2016-05-31T12:43:10.854464 #23533]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn)
bundler: failed to load command: unicorn (/var/www/danbooru2/shared/bundle/ruby/2.1.0/bin/unicorn)
LoadError: No such file to load -- gctools/oobgc
```
And it loops over and over again causing 99+% CPU usage.

Any help would be greatly appreciated. Thanks!

**Comment by r888888888** [comment]
```
No such file to load -- gctools/oobgc
```

This library is only loaded if the environment is production. The environment can be controlled in many ways but is usually defined by the RAILS_ENV environmental variable which should be set to production in a shell rc file somewhere on your system.

**Comment by cglmrfreeman** [comment]
Okay, but I am loading The development environment,  not the production environment.

**Comment by kdoshere** [comment]
Well, same problem here.

process fresh install of debian.

http://pastebin.com/wTv0Z5Ck <= INSTALLATION SCRIPT.log

http://pastebin.com/Wvyqrm6S <= bundle exec cap development deploy.log

http://pastebin.com/yVxqttxK <= unicorn.log

and now it

removing the dependency on ".config ru", appear to work .......
but, on  "post" shows the next error http://pastebin.com/yVxqttxK


thx for you time :)

**Comment by cglmrfreeman** [comment]
Any updates here? Paying for a server I can't use at the moment.

**Comment by r888888888** [comment]
You really don't want to be running in development mode for any production environment.

If you're just testing things out then don't use unicorn. You can run bundle exec rails server.

**Comment by cglmrfreeman** [comment]
I am not planning on running a production environment any time soon, as I have many changes to the software I need to make. If the delelopment mode shouldn't be run at all, I suggest you remove it.

**Comment by cglmrfreeman** [comment]
`bundle exec rails server.` yields similar results to `bundle exec cap development deploy`

Connecting to the server takes about 60 seconds for the Failbooru page to attempt to load, then it takes another 45 seconds to actually load the Failbooru page.

**Comment by r888888888** [comment]
this should be fixed now
