### ISSUE TITLE
Search by IP Exception

### ISSUE THREAD

**Issue by OOZ662** [r888888888/danbooru#2854]
Clicking the IP address link in a user's tag change history or using the IP search on the moderation dashboard gives this exception:
```
PG::UndefinedColumn exception raised
    ERROR: column "updater" does not exist LINE 1: SELECT COUNT(*) AS count_all, "updater" AS update FROM "poo... ^
    app/logical/moderator/ip_addr_search.rb:28:in `search_by_ip_addr'
    app/logical/moderator/ip_addr_search.rb:15:in `execute'
    app/controllers/moderator/ip_addrs_controller.rb:7:in `index'
```

**Comment by evazion** [comment]
It's already been fixed in #2849, will go out when albert redeploys the site.
