### ISSUE TITLE
Post Versions: "undefined method" error for specific edit

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2950]
Post Versions hits an "undefined method" error for page=b18386040 or any other page that includes the same edit as that, e.g. http://danbooru.donmai.us/post_versions.json?page=b18386040&limit=1 or http://danbooru.donmai.us/post_versions.json?page=b18386139&limit=100.

Exactly which method is "undefined" is different between JSON and non-JSON queries.

JSON:

    "message": "undefined method `tag_array' for nil:NilClass",
    "backtrace": ["/var/www/danbooru2/releases/20170330172854/app/models/post_archive.rb:142:in `changes'","/var/www/danbooru2/shared/bundle/ruby/2.3.0/gems/memoist-0.14.0/lib/memoist.rb:165:in `changes'","/var/www/danbooru2/releases/20170330172854/app/models/post_archive.rb:196:in `obsolete_added_tags'","/var/www/danbooru2/shared/bundle/ruby/2.3.0/gems/memoist-0.14.0/lib/memoist.rb:165:in `obsolete_added_tags'","/var/www/danbooru2/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/serialization.rb:110:in `block in serializable_hash'","/var/www/danbooru2/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.8/lib/active_model/serialization.rb:110:in `each'",

HTML:

    undefined method `visible?' for nil:NilClass
    app/views/post_versions/_listing.html.erb:39:in `block in _app_views_post_versions__listing_html_erb___3181077083507396852_70278193405800'
    app/views/post_versions/_listing.html.erb:20:in `_app_views_post_versions__listing_html_erb___3181077083507396852_70278193405800'
    app/views/post_versions/index.html.erb:8:in `_app_views_post_versions_index_html_erb___370901422545974141_70278200781280'
    app/controllers/post_versions_controller.rb:7:in `index'

**Comment by evazion** [comment]
This is the post version according to the post versions table in big query:

```json
 {
    "id": "18386039",
    "updated_at": "2017-03-30 23:18:02 UTC",
    "post_id": "2676545",
    "tags": "1girl ;) abstract_background animal_print artist_name bangs bodysuit breasts brown_eyes brown_hair bunny_print caesty chromatic_aberration clothes_writing d.va_(overwatch) facepaint facial_mark foreshortening full_body gloves headphones high_collar long_hair looking_at_viewer medium_breasts one_eye_closed overwatch pilot_suit purple_background ribbed_bodysuit shoulder_pads signature skin_tight smile solo swept_bangs v watermark web_address whisker_markings white_gloves",
    "added_tags": "1girl ;) abstract_background animal_print artist_name bangs bodysuit breasts brown_eyes brown_hair bunny_print caesty chromatic_aberration clothes_writing d.va_(overwatch) facepaint facial_mark foreshortening full_body gloves headphones high_collar long_hair looking_at_viewer medium_breasts one_eye_closed overwatch pilot_suit purple_background ribbed_bodysuit shoulder_pads signature skin_tight smile solo swept_bangs v watermark web_address whisker_markings white_gloves rating:s source:https://cdna.artstation.com/p/assets/images/images/005/343/748/original/s-caesty-160610-01.jpg",
    "removed_tags": "",
    "rating": "s",
    "parent_id": null,
    "source": "https://cdna.artstation.com/p/assets/images/images/005/343/748/original/s-caesty-160610-01.jpg",
    "updater_id": "342359",
    "updater_ip_addr": "<REDACTED>"
  }
```

The post id 2676545 doesn't exist: http://danbooru.donmai.us/posts/2676545. This causes `post` to be nil and an exception when the post version tries to access it.

I think what happened is that an upload was created, which created a new post, which sent a new post version to the archives service in the `after_save :create_version` callback, but then one of the following callbacks timed out, which caused the upload to ultimately fail and the db to rollback, but only after the post version had already been sent to the archives service.

cf: #2872, similar issue but with iqdb.

**Comment by BrokenEagle** [comment]
Ah, good, I was just about to report on this.  My [User Reports](http://danbooru.donmai.us/forum_topics/13112) script hit this snag a while back, and it took a while to drill down to which post version was causing the error.  I'll just skip the above post version for now.

**Comment by evazion** [comment]
@r888888888 post version 18386039 needs to be deleted from archives. This still fails: https://danbooru.donmai.us/post_versions.json?page=b18386040&limit=1.

**Comment by r888888888** [comment]
I've deleted it.

**Comment by RaisingK** [comment]
And now http://danbooru.donmai.us/post_versions.json?page=b18614786&limit=1

**Comment by evazion** [comment]
Still broken. Failed uploads can create post versions that belong to nonexistent posts:

![image](https://user-images.githubusercontent.com/8430473/63130973-c3e8a180-bf81-11e9-87c8-e6d9d6e8bc61.png)

https://danbooru.donmai.us/post_versions?search[id]=21622463
https://danbooru.donmai.us/post_versions?search[id]=21565813

In short: we need to use `after_commit :create_version` instead of `after_save :create_version`, but doing that breaks other things (#2972).
