### ISSUE TITLE
PG::ConnectionBad exception (could not translate host name "oumae.donmai.us" to address)

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3103]
I got this error on https://danbooru.donmai.us/post_versions?search%5Bpost_id%5D=2741803:

```
PG::ConnectionBad exception raised

could not translate host name "oumae.donmai.us" to address: Name or service not known
app/models/post_archive.rb:41:in `search'
app/controllers/post_versions_controller.rb:7:in `index'
```

I only got this error once, so it seems to have been a transient DNS error. Noting it here in case it comes up again.

**Comment by evazion** [comment]
I guess this was just a network hiccup. Anyway, if the archives database is unavailable then there's nothing much that can be done, except perhaps to catch the error more gracefully.
