### ISSUE TITLE
Aws::SQS::Errors::MissingParameter exception raised

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3151]
Tag edits and uploads give the error below. Possibly related to the FIFO queues from https://github.com/r888888888/archives/issues/6?

```
Aws::SQS::Errors::MissingParameter exception raised
The request must contain the parameter MessageGroupId.
app/logical/sqs_service.rb:15:in `send_message'
app/models/post_archive.rb:77:in `queue'
app/models/post.rb:1474:in `create_new_version'
app/models/post.rb:1463:in `create_version'
app/controllers/posts_controller.rb:49:in `update'
```

**Comment by r888888888** [comment]
Fixed.
