### ISSUE TITLE
NameError exception with post index

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3298]
The following exception gets returned when browsing the post index, although the post show doesn't have any issues.

```
NameError exception raised
undefined local variable or method `options' for PostPresenter:Class
app/presenters/post_presenter.rb:66:in `preview_class'
app/presenters/post_presenter.rb:24:in `preview'
app/presenters/post_set_presenters/base.rb:15:in `block in post_previews_html'
app/presenters/post_set_presenters/base.rb:14:in `post_previews_html'
app/views/posts/partials/index/_posts.html.erb:3:in `_app_views_posts_partials_index__posts_html_erb__1711211924540552024_69877348991040'
app/views/posts/index.html.erb:39:in `_app_views_posts_index_html_erb__4043735238263708226_69877346679280'
app/controllers/posts_controller.rb:16:in `index'
```

**Comment by r888888888** [comment]
whoops. fixed and deployed
