### ISSUE TITLE
Broken implications due to inconsistent descendent_names

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3343]
https://danbooru.donmai.us/tag_implications/4273.json

The `bunny_hood` -> `animal_hood` -> `hood` implication chain is broken. Adding `bunny_hood` doesn't add `hood`. The cause is that `hood` is not present in `bunny_hood`'s `descendant_names`.

Other tags having broken implications (not necessarily a comprehensive list):

```
bloomers_on_head
tenbou
strip_mahjong
ai_arctic_warfare
arisaka
mosin-nagant
mauser_98
cheytac_m200
bloomers_around_one_leg
bloomers_pull
g-string
beam_rifle
ray_gun
laser_rifle
bunny_hood
dog_hood
gyakuten_kenji_2
remington_msr
swimsuit_theft
tape_gag
over_the_nose_gag
clothes_gag
over_the_mouth_gag
mana_khemia_2
```

Running `TagImplication.find_each { |ti| ti.update_descendant_names; ti.save if ti.changed? }` should fix everything, but I don't know what the underlying cause was.

**Comment by r888888888** [comment]
Here's a complete list:

```
bloomers_on_head -> bloomers
tenbou -> mahjong
strip_mahjong -> mahjong
ai_arctic_warfare -> bolt_action
arisaka -> bolt_action
mosin-nagant -> bolt_action
mauser_98 -> bolt_action
cheytac_m200 -> bolt_action
bloomers_around_one_leg -> bloomers
bloomers_pull -> bloomers
g-string -> thong
beam_rifle -> energy_gun
ray_gun -> energy_gun
laser_rifle -> energy_gun
bunny_hood -> animal_hood
dog_hood -> animal_hood
gyakuten_kenji_2 -> gyakuten_kenji
remington_msr -> bolt_action
swimsuit_theft -> clothes_theft
tape_gag -> improvised_gag
over_the_nose_gag -> cloth_gag
clothes_gag -> improvised_gag
over_the_mouth_gag -> cloth_gag
mana_khemia_2 -> mana_khemia_(series)
```

**Comment by r888888888** [comment]
```
irb(main):005:0>  TagImplication.find_each { |ti| ti.update_descendant_names; ti.save if ti.changed? }
WARNING: Can't mass-assign protected attributes for TagImplication: descendant_names
	app/models/tag_implication.rb:54:in `update_descendant_names!'
	app/models/tag_implication.rb:59:in `block in update_descendant_names_for_parents'
	app/models/tag_implication.rb:58:in `update_descendant_names_for_parents'
```

Interesting. I've changed it to an `update_attribute`.
