### ISSUE TITLE
Change category on Bulk Update Requests are broken

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3380]
```
Unknown token: change_category
app/models/bulk_update_request.rb:182:in `block in script_with_links'
app/models/bulk_update_request.rb:173:in `map'
app/models/bulk_update_request.rb:173:in `script_with_links'
app/models/bulk_update_request.rb:168:in `reason_with_link'
app/models/bulk_update_request.rb:117:in `create_forum_topic'
app/controllers/bulk_update_requests_controller.rb:13:in `create'
```
Seems like ``change_category`` wasn't added to the case statement in that function.

**Comment by evazion** [comment]
Fixed in 3df404d. Also fixed it being missing in a couple other places.
