### ISSUE TITLE
Spurious email notifications

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3474]
Unbreakable reported that he received email notifications for dmails that don't exist:

> Hmm, I just got 2 e-mails that I got a new DMail (both were the same) but they don't show up on Danbooru. When I click "View message" I get either 

    ActiveRecord::RecordNotFound exception raised
    Couldn't find Dmail with 'id'=1218858
    app/controllers/dmails_controller.rb:32:in `show'

> for the first mail and 

    ActiveRecord::RecordNotFound exception raised
    Couldn't find Dmail with 'id'=1218860
    app/controllers/dmails_controller.rb:32:in `show'

> for the second one

**Comment by evazion** [comment]
I believe the cause is sending the email in an `after_create` hook. The email is sent before the dmail has been successfully committed to the database, so if there's a database timeout the dmail creation will fail but the email has already been sent.
