### ISSUE TITLE
IQDB service is completely down

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3502]
The IQDB service stopped working at around 2300 PST.  I checked it this morning and it's still not working.  

message: "HTTP error code: 502 Bad Gateway"
backtrace:
```
/var/www/danbooru2/releases/20180103001443/app/logical/iqdb/download.rb:46:in `find_similar'
/var/www/danbooru2/releases/20180103001443/app/controllers/iqdb_queries_controller.rb:53:in `create_by_post'
```

Also, I can't remember if it's already been suggested, but it might be useful if there was a status page for things like this to let users know whether a service is down or not.  Something like sending a heartbeat  between Danbooru and its supporting servers.  Also, instead of creating a new issue every time one of the servers go down, would it be better to have one single issue that they all get reported on?

**Comment by r888888888** [comment]
It's up again.

**Comment by BrokenEagle** [comment]
IQDB service is down again.  This was first noticed this morning, as it was working last night.

**Comment by nonamethanks** [comment]
@r888888888 in case you weren't aware, it's down again with error 500.
