### ISSUE TITLE
Listbooru service is completely down

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3505]
Getting the following error when using the `search:` metatag or when visiting one's own account page.
```
RuntimeError exception raised

HTTP error code: 502 Bad Gateway
app/models/saved_search.rb:37:in `block in post_ids'
app/logical/cache.rb:18:in `get'
app/models/saved_search.rb:22:in `post_ids'
```

**Comment by r888888888** [comment]
It's up again.

**Comment by BrokenEagle** [comment]
@r888888888 

Getting a similar error as the above when doing the same things as before.

```
HTTP error code: 502 Bad Gateway
app/models/saved_search.rb:37:in `block in post_ids'
app/logical/cache.rb:18:in `get'
app/models/saved_search.rb:22:in `post_ids'
app/logical/post_query_builder.rb:76:in `block in add_saved_search_relation'
app/logical/post_query_builder.rb:72:in `each'
app/logical/post_query_builder.rb:72:in `add_saved_search_relation'
app/logical/post_query_builder.rb:201:in `build'
app/models/post.rb:1634:in `tag_match'
app/presenters/user_presenter.rb:47:in `posts_for_saved_search_category'
app/views/users/_post_summary.html.erb:36:in `block in _app_views_users__post_summary_html_erb___2568463808609239324_47347301129380'
app/views/users/_post_summary.html.erb:28:in `each'
app/views/users/_post_summary.html.erb:28:in `_app_views_users__post_summary_html_erb___2568463808609239324_47347301129380'
app/views/users/show.html.erb:9:in `_app_views_users_show_html_erb__2618623042193355887_47347295610980'
app/controllers/users_controller.rb:40:in `show'
```
