### ISSUE TITLE
Issue running command "bundle exec rake db:create db:migrate"

### ISSUE THREAD

**Issue by AriinPHD** [r888888888/danbooru#3571]
Ubuntu version 16.04.3 LTS (codename xenial)

Running the command `bundle exec rake db:create db:migrate` returns error.

Anything I'm missing?

Following the installation instructions there were no mentions of a configuration folder in the user home folder.

```
rd@srvapp01:~$ bundle exec rake db:create db:migrate
rake aborted!
LoadError: cannot load such file -- /home/rd/config/application
/home/rd/Rakefile:4:in `require'
/home/rd/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
rd@srvapp01:~$ bundle exec rake db:create db:migrate --trace
rake aborted!
LoadError: cannot load such file -- /home/rd/config/application
/home/rd/Rakefile:4:in `require'
/home/rd/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:703:in `raw_load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:82:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

**Comment by evazion** [comment]
It can't find the file [config/application.rb](https://github.com/r888888888/danbooru/blob/master/config/application.rb). Make sure that you've [cloned the repository to your computer](https://help.github.com/articles/cloning-a-repository/) and that you're running `bundle exec rake db:create db:migrate` inside the right directory.

**Comment by AriinPHD** [comment]
OK, thanks.

According to documentation, these were commands I could run if I did not
wish to clone the repo. I hope you can please update either docs or the
installer program.
