### ISSUE TITLE
Webm / mp4 uploads broken

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3607]
https://danbooru.donmai.us/uploads/1799333:

```
/var/www/danbooru2/releases/20180405215015/app/models/upload.rb:263:in `generate_resizes'
/var/www/danbooru2/releases/20180405215015/app/models/upload.rb:158:in `distribute_files'
/var/www/danbooru2/releases/20180405215015/app/models/upload.rb:143:in `create_post_from_upload'
/var/www/danbooru2/releases/20180405215015/app/models/upload.rb:170:in `process!'
```

Bug is a typo in `generate_resizes`.

**Comment by evazion** [comment]
Added some webm / mp4 upload tests too (01eda51020653d59a20e144e05f72f869009dc11). Will need to `s/FactoryGirl/FactoryBot/` when rails 5 is merged.
