### ISSUE TITLE
Tag similarity on autocomplete no longer working

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3636]
Pointed out by Unbreakable on Discord.  After looking into this, I got the following response:

```json
{
    "success": false,
    "message": "undefined method `sanitize' for #\u003cClass:0x0000560d58a07e98\u003e\nDid you mean?  sanitize_sql",
    "backtrace": ["
        /var/www/danbooru2/shared/bundle/ruby/2.5.0/gems/activerecord-5.1.6/lib/active_record/dynamic_matchers.rb:22:in `method_missing'",
        /var/www/danbooru2/releases/20180412233323/app/models/tag.rb:855:in `order_similarity'",
        ....
        ....
        "]
}
```

So it seems like sanitize is no longer a valid method in Rails 5...?
https://github.com/r888888888/danbooru/blob/master/app/models/tag.rb#L855

**Comment by evazion** [comment]
Ref: https://github.com/rails/rails/issues/28947.
