### ISSUE TITLE
ActionView::Template::Error exception raised

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3645]
Heya, I've been having this issue for a short while now, I thought it might have to do with my system being a tad outdated so I updated everything today but I'm still having this issue, I'm getting the following error:
```

    Couldn't find User with 'id'=
    app/models/post.rb:79:in `keeper'
    app/views/posts/partials/show/_information.html.erb:3:in `_app_views_posts_partials_show__information_html_erb__2993552881508013272_47006913635060'
    app/views/posts/show.html.erb:14:in `_app_views_posts_show_html_erb__870736414938273141_47006913310920'
    app/controllers/posts_controller.rb:34:in `show'

```
**WARNING** NSFW images.
I'm getting it on random pages set as "parent" https://atfbooru.ninja/posts/102538 that one is set to the parent from https://atfbooru.ninja/posts/233985.

I generated a SQL Insert with the above post:

```
INSERT INTO public.posts
(id, created_at, updated_at, up_score, down_score, score, "source", md5, rating, is_note_locked, is_rating_locked, is_status_locked, is_pending, is_flagged, is_deleted, uploader_id, uploader_ip_addr, approver_id, fav_string, pool_string, last_noted_at, last_comment_bumped_at, fav_count, tag_string, tag_index, tag_count, tag_count_general, tag_count_artist, tag_count_character, tag_count_copyright, file_ext, file_size, image_width, image_height, parent_id, has_children, is_banned, pixiv_id, last_commented_at, has_active_children, bit_flags, tag_count_meta, keeper_data)
VALUES(102538, '2016-04-03 08:25:27.667', '2018-04-16 12:40:13.729', 0, 0, 0, '', 'b6c34d87cb494930fe31df224ad1cb78', 'e', false, false, false, false, false, false, 1, 93.190.142.151, NULL, 'fav:619 fav:3750', '', NULL, NULL, 2, '1girl blue_eyes blush bow brown_hair crossed_fingers dutch_angle english flat_chest groin heart loli navel nipples nude open_mouth original pussy small_breasts solo thighs tongue twintails wancho', '1girl':1 'blue_eyes':2 'blush':3 'bow':4 'brown_hair':5 'crossed_fingers':6 'dutch_angle':7 'english':8 'fav:3750':26 'fav:619':25 'flat_chest':9 'groin':10 'heart':11 'loli':12 'navel':13 'nipples':14 'nude':15 'open_mouth':16 'original':17 'pussy':18 'small_breasts':19 'solo':20 'thighs':21 'tongue':22 'twintails':23 'wancho':24, 24, 22, 1, 0, 1, 'jpg', 319954, 880, 960, NULL, true, false, NULL, NULL, true, 0, 0, '{"uid":null}');
```

**Comment by Iratu** [comment]
Thanks, that seemed to have fixed that issue. I still have one more issue;
```
ActionView::Template::Error exception raised

    PG::UndefinedObject: ERROR: text search configuration "danbooru" does not exist LINE 1: ...d WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru'... ^ : SELECT "posts".* FROM "posts" INNER JOIN favorites ON favorites.post_id = posts.id WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru', E'(''fav:1'')')) AND (favorites.user_id % 100 = 1 and favorites.user_id = 1) ORDER BY favorites.id DESC, posts.id DESC LIMIT $1
    app/views/users/_post_summary.html.erb:20:in `_app_views_users__post_summary_html_erb___1730948170042613806_46986538136480'
    app/views/users/show.html.erb:9:in `_app_views_users_show_html_erb___4194572733708853451_46986531474280'
    app/controllers/users_controller.rb:40:in `show'
```
This appears when trying to access "My Account" and trying to search for stuff.

**Comment by evazion** [comment]
What does `psql danbooru2 -c '\dF+ danbooru'` say? You should see something like this:

```
$ psql danbooru2 -c '\dF+ danbooru'
Text search configuration "public.danbooru"
Parser: "public.testparser"
 Token | Dictionaries
-------+--------------
 word  | simple
```

If nothing's there you may need to reinstall the `test_parser` extension (see INSTALL.debian).

**Comment by Iratu** [comment]
I've tried installing it, it shows up in the extension database but it doesn't load it

```danbooru@server:/usr/share/postgresql/9.6/extension$ psql danbooru2 -c '\dF+ danbooru'
Did not find any text search configuration named "danbooru".
danbooru@server:/usr/share/postgresql/9.6/extension$ 
```

```
danbooru@server:/usr/share/postgresql/9.6/extension$ ls
adminpack--1.0.sql               cube--unpackaged--1.0.sql           hstore--1.4.sql                       moddatetime--1.0.sql                  pg_stat_statements--1.4.sql              pgstattuple--1.4.sql              test_parser.control
adminpack.control                cube.control                        hstore--unpackaged--1.0.sql           moddatetime--unpackaged--1.0.sql      pg_stat_statements--unpackaged--1.0.sql  pgstattuple--unpackaged--1.0.sql  timetravel--1.0.sql
autoinc--1.0.sql                 dblink--1.0--1.1.sql                hstore.control                        moddatetime.control                   pg_stat_statements.control               pgstattuple.control               timetravel--unpackaged--1.0.sql
autoinc--unpackaged--1.0.sql     dblink--1.1--1.2.sql                insert_username--1.0.sql              pageinspect--1.0--1.1.sql             pg_trgm--1.0--1.1.sql                    plpgsql--1.0.sql                  timetravel.control
autoinc.control                  dblink--1.2.sql                     insert_username--unpackaged--1.0.sql  pageinspect--1.1--1.2.sql             pg_trgm--1.1--1.2.sql                    plpgsql--unpackaged--1.0.sql      tsearch2--1.0.sql
bloom--1.0.sql                   dblink--unpackaged--1.0.sql         insert_username.control               pageinspect--1.2--1.3.sql             pg_trgm--1.2--1.3.sql                    plpgsql.control                   tsearch2--unpackaged--1.0.sql
bloom.control                    dblink.control                      intagg--1.0--1.1.sql                  pageinspect--1.3--1.4.sql             pg_trgm--1.3.sql                         postgres_fdw--1.0.sql             tsearch2.control
btree_gin--1.0.sql               dict_int--1.0.sql                   intagg--1.1.sql                       pageinspect--1.4--1.5.sql             pg_trgm--unpackaged--1.0.sql             postgres_fdw.control              tsm_system_rows--1.0.sql
btree_gin--unpackaged--1.0.sql   dict_int--unpackaged--1.0.sql       intagg--unpackaged--1.0.sql           pageinspect--1.5.sql                  pg_trgm.control                          refint--1.0.sql                   tsm_system_rows.control
btree_gin.control                dict_int.control                    intagg.control                        pageinspect--unpackaged--1.0.sql      pg_visibility--1.0--1.1.sql              refint--unpackaged--1.0.sql       tsm_system_time--1.0.sql
btree_gist--1.0--1.1.sql         dict_xsyn--1.0.sql                  intarray--1.0--1.1.sql                pageinspect.control                   pg_visibility--1.1.sql                   refint.control                    tsm_system_time.control
btree_gist--1.1--1.2.sql         dict_xsyn--unpackaged--1.0.sql      intarray--1.1--1.2.sql                pg_buffercache--1.0--1.1.sql          pg_visibility.control                    seg--1.0--1.1.sql                 unaccent--1.0--1.1.sql
btree_gist--1.2.sql              dict_xsyn.control                   intarray--1.2.sql                     pg_buffercache--1.1--1.2.sql          pgcrypto--1.0--1.1.sql                   seg--1.1.sql                      unaccent--1.1.sql
btree_gist--unpackaged--1.0.sql  earthdistance--1.0--1.1.sql         intarray--unpackaged--1.0.sql         pg_buffercache--1.2.sql               pgcrypto--1.1--1.2.sql                   seg--unpackaged--1.0.sql          unaccent--unpackaged--1.0.sql
btree_gist.control               earthdistance--1.1.sql              intarray.control                      pg_buffercache--unpackaged--1.0.sql   pgcrypto--1.2--1.3.sql                   seg.control                       unaccent.control
chkpass--1.0.sql                 earthdistance--unpackaged--1.0.sql  isn--1.0--1.1.sql                     pg_buffercache.control                pgcrypto--1.3.sql                        sslinfo--1.0--1.1.sql             uuid-ossp--1.0--1.1.sql
chkpass--unpackaged--1.0.sql     earthdistance.control               isn--1.1.sql                          pg_freespacemap--1.0--1.1.sql         pgcrypto--unpackaged--1.0.sql            sslinfo--1.1--1.2.sql             uuid-ossp--1.1.sql
chkpass.control                  file_fdw--1.0.sql                   isn--unpackaged--1.0.sql              pg_freespacemap--1.1.sql              pgcrypto.control                         sslinfo--1.2.sql                  uuid-ossp--unpackaged--1.0.sql
citext--1.0--1.1.sql             file_fdw.control                    isn.control                           pg_freespacemap--unpackaged--1.0.sql  pgrowlocks--1.0--1.1.sql                 sslinfo--unpackaged--1.0.sql      uuid-ossp.control
citext--1.1--1.2.sql             fuzzystrmatch--1.0--1.1.sql         lo--1.0--1.1.sql                      pg_freespacemap.control               pgrowlocks--1.1--1.2.sql                 sslinfo.control                   xml2--1.0--1.1.sql
citext--1.2--1.3.sql             fuzzystrmatch--1.1.sql              lo--1.1.sql                           pg_prewarm--1.0--1.1.sql              pgrowlocks--1.2.sql                      tablefunc--1.0.sql                xml2--1.1.sql
citext--1.3.sql                  fuzzystrmatch--unpackaged--1.0.sql  lo--unpackaged--1.0.sql               pg_prewarm--1.1.sql                   pgrowlocks--unpackaged--1.0.sql          tablefunc--unpackaged--1.0.sql    xml2--unpackaged--1.0.sql
citext--unpackaged--1.0.sql      fuzzystrmatch.control               lo.control                            pg_prewarm.control                    pgrowlocks.control                       tablefunc.control                 xml2.control
citext.control                   hstore--1.0--1.1.sql                ltree--1.0--1.1.sql                   pg_stat_statements--1.0--1.1.sql      pgstattuple--1.0--1.1.sql                tcn--1.0.sql
cube--1.0--1.1.sql               hstore--1.1--1.2.sql                ltree--1.1.sql                        pg_stat_statements--1.1--1.2.sql      pgstattuple--1.1--1.2.sql                tcn.control
cube--1.1--1.2.sql               hstore--1.2--1.3.sql                ltree--unpackaged--1.0.sql            pg_stat_statements--1.2--1.3.sql      pgstattuple--1.2--1.3.sql                test_parser--1.0.sql
cube--1.2.sql                    hstore--1.3--1.4.sql                ltree.control                         pg_stat_statements--1.3--1.4.sql      pgstattuple--1.3--1.4.sql                test_parser--unpackaged--1.0.sql
```

**Comment by evazion** [comment]
You may need to run this again:

https://github.com/r888888888/danbooru/blob/9cafffd20ad3a8e60bb52432b79fd372647b44c0/db/structure.sql#L369-L421

**Comment by Iratu** [comment]
Thanks for your help, I fixed it by restoring a backup made before upgrading to Debian 9.4 upgraded again and then install the test_parser before upgrading PostgreSQL 9.4 to 9.6.
