### ISSUE TITLE
Exception raised on forum threads with votable forum posts

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3686]
Getting the following exception when trying to visit a forum thread with a votable forum post:

```
no implicit conversion of nil into String
app/models/forum_post.rb:136:in `votable?'
app/views/forum_posts/_forum_post.html.erb:47:in `_app_views_forum_posts__forum_post_html_erb__2056788752877131050_46955441904140'
app/views/forum_posts/_listing.html.erb:6:in `block in _app_views_forum_posts__listing_html_erb__4096560397800578015_46955441957440'
app/views/forum_posts/_listing.html.erb:5:in `_app_views_forum_posts__listing_html_erb__4096560397800578015_46955441957440'
app/views/forum_topics/show.html.erb:23:in `_app_views_forum_topics_show_html_erb___527365184086828512_46955442016660'
app/controllers/forum_topics_controller.rb:50:in `show'
```

**Comment by BrokenEagle** [comment]
@r888888888 I just checked after the recent push, and the forum topics that were broke, are still broke.
