### ISSUE TITLE
Template exception on post index

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3736]
Getting the following error when visiting the post index with no search terms:
- https://danbooru.donmai.us/posts
- https://danbooru.donmai.us
```
ActionView::Template::Error exception raised
SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
app/logical/popular_search_service.rb:30:in `block in fetch_data'
app/logical/cache.rb:18:in `get'
app/logical/popular_search_service.rb:28:in `fetch_data'
app/logical/popular_search_service.rb:22:in `tags'
app/presenters/post_set_presenters/post.rb:34:in `popular_tags'
app/presenters/post_set_presenters/post.rb:26:in `related_tags'
app/presenters/post_set_presenters/post.rb:11:in `tag_set_presenter'
app/presenters/post_set_presenters/post.rb:71:in `tag_list_html'
app/views/posts/index.html.erb:12:in `_app_views_posts_index_html_erb__3863487507109390482_70265030457620'
app/controllers/posts_controller.rb:17:in `index'
```

**Comment by r888888888** [comment]
I renewed the SSL cert on isshiki. Should be fine now.

**Comment by BrokenEagle** [comment]
Yeah, I'm not getting that error anymore, and the ones I talked to on Discord aren't either.
