### ISSUE TITLE
Validation failed: Md5 confirmation doesn't match Md5 when uploading from URL

### ISSUE THREAD

**Issue by meoberto** [r888888888/danbooru#3750]
I have so far tried uploading pictures to my instance of Danbooru from 2 external sources (pixiv and niconico seiga) and a file. The file upload went without any issues, whereas both the pixiv and seiga uploads had the same issue. I am completely lost so i can only provide logs.

This is what I get on the browser window:
```

ActiveRecord::RecordInvalid exception raised

    Validation failed: Md5 confirmation doesn't match Md5
    app/logical/upload_service.rb:500:in `start!'
    app/controllers/uploads_controller.rb:54:in `create'

```

And this is the output when running danbooru with the development environment
```
[PID:7302] Started POST "/uploads" for 127.0.0.1 at 2018-06-17 20:25:49 +0000
[PID:7302] Processing by UploadsController#create as HTML
[PID:7302]   Parameters: {"utf8"=>"✓", "authenticity_token"=>[removed], "url"=>"", "ref"=>"", "normalized_url"=>"", "upload"=>{"md5_confirmation"=>"", "referer_url"=>"", "as_pending"=>"0", "source"=>"http://seiga.nicovideo.jp/seiga/im8224590", "rating"=>"s", "parent_id"=>"", "artist_commentary_title"=>"長良ちゃん", "artist_commentary_desc"=>"好きだ…", "include_artist_commentary"=>"1", "tag_string"=>"tagme"}}
[PID:7302]   User Load (6.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[PID:7302]   ↳ app/logical/session_loader.rb:82
[PID:7302]    (0.8ms)  set statement_timeout = 9000
[PID:7302]   ↳ app/logical/session_loader.rb:44
[PID:7302]   TokenBucket Load (1.3ms)  SELECT  "token_buckets".* FROM "token_buckets" WHERE "token_buckets"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
[PID:7302]   ↳ app/controllers/application_controller.rb:60
[PID:7302]   TokenBucket Update All (2.2ms)  UPDATE "token_buckets" SET token_count = least(token_count + (4 * extract(epoch from '2018-06-17 20:25:49.569930' - last_touched_at)), 60), last_touched_at = '2018-06-17 20:25:49.569930' WHERE "token_buckets"."user_id" = $1  [["user_id", 1]]
[PID:7302]   ↳ app/models/token_bucket.rb:19
[PID:7302]   TokenBucket Update All (1.5ms)  UPDATE "token_buckets" SET token_count = greatest(0, token_count - 1) WHERE "token_buckets"."user_id" = $1  [["user_id", 1]]
[PID:7302]   ↳ app/models/token_bucket.rb:27
[PID:7302]   IpBan Exists (1.0ms)  SELECT  1 AS one FROM "ip_bans" WHERE (ip_addr = '127.0.0.1') LIMIT $1  [["LIMIT", 1]]
[PID:7302]   ↳ app/models/ip_ban.rb:15
[PID:7302]   Upload Exists (2.4ms)  SELECT  1 AS one FROM "uploads" WHERE "uploads"."status" = $1 AND "uploads"."source" = $2 LIMIT $3  [["status", "preprocessing"], ["source", "http://seiga.nicovideo.jp/seiga/im8224590"], ["LIMIT", 1]]
[PID:7302]   ↳ app/logical/upload_service.rb:235
[PID:7302]   Upload Load (3.3ms)  SELECT  "uploads".* FROM "uploads" WHERE "uploads"."status" IN ($1, $2) AND "uploads"."source" = $3 ORDER BY "uploads"."id" ASC LIMIT $4  [["status", "preprocessed"], ["status", "preprocessing"], ["source", "http://seiga.nicovideo.jp/seiga/im8224590"], ["LIMIT", 1]]
[PID:7302]   ↳ app/logical/upload_service.rb:245
[PID:7302]    (0.7ms)  BEGIN
[PID:7302]   ↳ app/logical/upload_service.rb:500
[PID:7302]   User Load (3.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
[PID:7302]   ↳ app/logical/upload_service.rb:500
[PID:7302]    (0.8ms)  ROLLBACK
[PID:7302]   ↳ app/logical/upload_service.rb:500
[PID:7302]   Rendering static/error.html.erb within layouts/blank
[PID:7302]   Rendered static/error.html.erb within layouts/blank (2.7ms)
[PID:7302] Completed 500 Internal Server Error in 391ms (Views: 250.9ms | ActiveRecord: 23.8ms)
```

All of this is running the latest commit [a9c4210](https://github.com/r888888888/danbooru/commit/a9c4210bb57ff670fd6dbcd12cdff80aecd0fb94)

**Comment by r888888888** [comment]
This should be fixed in cc24b0a54f6a6d0c0edf8ead8a191f758b5e0795
