### ISSUE TITLE
Post replacements: ActiveRecord::RecordNotUnique exception

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3770]
I tried to replace post #3167334 with its own source but got an ActiveRecord::RecordNotUnique exception because that post had the same source as... itself.  I had to clear the post's source first to push the replacement through.

    A post with source http://www.compileheart.com/neptune/yu-shanep/img/chara/chrom.png already exists
    app/logical/upload_service.rb:314:in `block in start!'
    app/logical/current_user.rb:10:in `scoped'
    app/logical/current_user.rb:32:in `as_system'
    app/logical/upload_service.rb:312:in `start!'
    app/logical/upload_service.rb:434:in `process!'
    app/models/post.rb:1404:in `block in replace!'
    app/models/post.rb:1401:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

**Comment by RaisingK** [comment]
For some reason, clearing the source didn't work for post #3180409, though:

    A completed upload with source https://i.pximg.net/img-original/img/2018/05/01/00/23/11/68500167_p0.png already exists
    app/logical/upload_service.rb:323:in `start!'
    app/logical/upload_service.rb:445:in `process!'
    app/models/post.rb:1404:in `block in replace!'
    app/models/post.rb:1401:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

**Comment by RaisingK** [comment]
Attempting to replace post #3181453 (corrupted):

    ActiveRecord::RecordNotUnique exception raised
    PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_posts_on_md5" DETAIL: Key (md5)=(7ee9143bc79faa5f0c5de0acda8be062) already exists. : UPDATE "posts" SET "source" = $1, "tag_string" = $2, "file_size" = $3, "md5" = $4, "tag_count" = $5, "updated_at" = $6, "tag_count_meta" = $7 WHERE "posts"."id" = $8
    app/logical/upload_service.rb:491:in `process!'
    app/models/post.rb:1404:in `block in replace!'
    app/models/post.rb:1401:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'
