### ISSUE TITLE
Error in logfile

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3834]
G'day so I was trying to find an error happening on my Fork and I stumbled on the following error being spammed a lot.

```
018-08-24T01:27:33.187626 #29896] FATAL -- : [023629b4-1916-4520-ae60-92d51c759375]
F, [2018-08-24T01:27:33.187765 #29896] FATAL -- : [023629b4-1916-4520-ae60-92d51c759375] ActionController::RoutingError (No route matches [POST] "/post_views"):
F, [2018-08-24T01:27:33.187856 #29896] FATAL -- : [023629b4-1916-4520-ae60-92d51c759375]
F, [2018-08-24T01:27:33.187976 #29896] FATAL -- : [023629b4-1916-4520-ae60-92d51c759375] actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
[023629b4-1916-4520-ae60-92d51c759375] railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
[023629b4-1916-4520-ae60-92d51c759375] activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[023629b4-1916-4520-ae60-92d51c759375] activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
[023629b4-1916-4520-ae60-92d51c759375] activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
[023629b4-1916-4520-ae60-92d51c759375] railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/method_override.rb:22:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/runtime.rb:22:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] actionpack (5.2.0) lib/action_dispatch/middleware/ssl.rb:74:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] railties (5.2.0) lib/rails/engine.rb:524:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/common_logger.rb:33:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/chunked.rb:54:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] rack (2.0.5) lib/rack/content_length.rb:15:in `call'
[023629b4-1916-4520-ae60-92d51c759375] newrelic_rpm (5.0.0.342) lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
[023629b4-1916-4520-ae60-92d51c759375] unicorn (5.4.0) lib/unicorn/http_server.rb:606:in `process_client'
[023629b4-1916-4520-ae60-92d51c759375] unicorn-worker-killer (0.4.4) lib/unicorn/worker_killer.rb:92:in `process_client'
[023629b4-1916-4520-ae60-92d51c759375] unicorn (5.4.0) lib/unicorn/http_server.rb:701:in `worker_loop'
[023629b4-1916-4520-ae60-92d51c759375] unicorn (5.4.0) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
[023629b4-1916-4520-ae60-92d51c759375] unicorn (5.4.0) lib/unicorn/http_server.rb:563:in `maintain_worker_count'
[023629b4-1916-4520-ae60-92d51c759375] unicorn (5.4.0) lib/unicorn/http_server.rb:293:in `join'
[023629b4-1916-4520-ae60-92d51c759375] unicorn (5.4.0) bin/unicorn:126:in `<top (required)>'
[023629b4-1916-4520-ae60-92d51c759375] /var/www/danbooru2/shared/bundle/ruby/2.5.0/bin/unicorn:23:in `load'
[023629b4-1916-4520-ae60-92d51c759375] /var/www/danbooru2/shared/bundle/ruby/2.5.0/bin/unicorn:23:in `<top (required)>'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/cli/exec.rb:74:in `load'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/cli/exec.rb:74:in `kernel_load'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/cli/exec.rb:28:in `run'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/cli.rb:424:in `exec'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/cli.rb:27:in `dispatch'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/cli.rb:18:in `start'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) exe/bundle:30:in `block in <top (required)>'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
[023629b4-1916-4520-ae60-92d51c759375] bundler (1.16.4) exe/bundle:22:in `<top (required)>'
[023629b4-1916-4520-ae60-92d51c759375] /home/danbooru/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
[023629b4-1916-4520-ae60-92d51c759375] /home/danbooru/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
```

I'm not really certain what the error is for, I think it is for newrelic which I'm not using so I disabled it as far as I'm aware.

**Comment by Iratu** [comment]
It appears to have been fixed, I kinda forgot I posted this issue, thanks for the fix :+1:
