### ISSUE TITLE
Trying to upload dead tweets via bookmarklet returns bare error page even if actual image is alive

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3836]
It seems the bookmarklet just gives up in those cases, which is troublesome for people like me who scrape for and save tweets. Basically whenever I want to upload a deleted tweet I can't generate urls with "ref=<twitter_id>" in the url, because the displayed page won't reach the upload form, forcing me to manually add the source afterwards. 

The displayed error is 
```
No status found with that ID.
app/logical/sources/strategies/twitter.rb:26:in `api_response'
app/logical/sources/strategies/twitter.rb:18:in `artist_name'
app/logical/sources/strategies/twitter.rb:14:in `normalized_url'
app/logical/sources/strategies/twitter.rb:10:in `referer_url'
app/logical/sources/site.rb:33:in `referer_url'
app/views/uploads/new.html.erb:25:in `block in _app_views_uploads_new_html_erb__2843458151513120575_70134278689180'
app/views/uploads/new.html.erb:20:in `_app_views_uploads_new_html_erb__2843458151513120575_70134278689180'
app/controllers/uploads_controller.rb:11:in `new'
```

[Example page](https://danbooru.donmai.us/uploads/new?url=http%3A%2F%2Fnonamethanks.berry.seedhost.eu%2Fscraping%2Fgalleries%2Ffeed%2Ffeeds%2Ftwitter%2Fimages%2FDgvzBTEV4AAHjj7.jpg&ref=https%3A%2F%2Ftwitter.com%2Fslugbox%2Fstatus%2F1012169751022526464)

It'd be neat if the upload page would still be displayed. The upload could still fail if there's no way to extract the image, but there's no reason why such error couldn't be displayed inside the upload form like it used to be before the Rails 5 update of a couple of months ago.

**Comment by nonamethanks** [comment]
https://github.com/r888888888/danbooru/commit/e10df5bdf75d31e65b2faf82d5218cedc6963f3e alleviates this problem so I guess this can be considered low priority now, as there's no means for non-tech-savvy users to open bookmarklets for dead tweets unless they for some reason still have the tab open.
