### ISSUE TITLE
Sources::Error exception raised when adding stacc URL

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3863]
Attempting to add http://www.pixiv.net/stacc/akihikon to artist #175147 gets me:

    Sources::Error exception raised

    Couldn't get illust ID from URL (http://www.pixiv.net/stacc/akihikon, )
    app/logical/sources/strategies/pixiv.rb:216:in `illust_id'
    app/logical/sources/strategies/pixiv.rb:124:in `normalizable_for_artist_finder?'
    app/models/artist_url.rb:37:in `normalize'
    app/models/artist_url.rb:109:in `normalize'
    app/models/artist.rb:187:in `block (2 levels) in save_urls'
    app/models/artist.rb:186:in `map'
    app/models/artist.rb:186:in `block in save_urls'
    app/models/artist.rb:184:in `save_urls'
    app/controllers/artists_controller.rb:64:in `update'

**Comment by nonamethanks** [comment]
issue #3856
