### ISSUE TITLE
DeviantArt: 'Absolute URI missing hierarchical segment: 'http:#'

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3967]
The dA strategy fails when fetching the commentary for some sources:

* https://danbooru.donmai.us/source.json?url=https://img00.deviantart.net/233d/i/2018/267/2/6/bowsette_sketch_by_raikoart-dcnmnej.png

```
  {
    "success": false,
    "message": "Absolute URI missing hierarchical segment: 'http:#'",
    "backtrace": ["app/logical/sources/strategies/deviant_art.rb:169:in `block in dtext_artist_commentary_desc'","app/logical/d_text.rb:54:in `block in from_html'","app/logical/d_text.rb:53:in `map'","app/logical/d_text.rb:53:in `from_html'","app/logical/d_text.rb:99:in `block in from_html'","app/logical/d_text.rb:53:in `map'","app/logical/d_text.rb:53:in `from_html'","app/logical/sources/strategies/deviant_art.rb:147:in `dtext_artist_commentary_desc'","app/logical/sources/strategies/base.rb:234:in `to_h'","app/controllers/sources_controller.rb:7:in `show'"]
  }
```

**Comment by lllusion3469** [comment]
This happens because of the `<a href="#"></a>` in `artist_commentary_desc`.
As the url is just an empty `fragment` (`#`) and missing a path and a host, you can't actually add a `scheme` because that would result in an invalid URI (either that or [this](https://github.com/sporkmonger/addressable/blob/6add2b7a5457bbe64be07e8626a87ed607a6868a/lib/addressable/uri.rb#L2427) is wrong).

A simple way to fix it would be this:
```diff
--- a/app/logical/sources/strategies/deviant_art.rb
+++ b/app/logical/sources/strategies/deviant_art.rb
@@ -165,7 +165,7 @@ module Sources
 
             # href may be missing the `http://` bit (ex: `inprnt.com`, `//inprnt.com`). Add it if missing.
             uri = Addressable::URI.heuristic_parse(element["href"]) rescue nil
-            if uri.present?
+            if uri.present? && (uri.path.present? || uri.path.present?)
               uri.scheme ||= "http"
               element["href"] = uri.to_s
             end
```
though you may want to skip the element altogether instead of just not modifying the `href` (not sure, doesn't show up anyways with this patch).
