### ISSUE TITLE
Twitter: undefined method `first' for nil:NilClass

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3984]
The Twitter strategy fails to get the `image_url` for this tweet (NSFW):

* https://twitter.com/oniotaku101/status/762746499386122240
* https://danbooru.donmai.us/uploads/new?url=https://twitter.com/oniotaku101/status/762746499386122240

```
Upload #2109419
Date: 2018-11-09 20:52:24 -0600
Source: https://twitter.com/oniotaku101/status/762746499386122240
Tags: tagme
An error occurred: error: NoMethodError - undefined method `first' for nil:NilClass

app/logical/sources/strategies/base.rb:75:in `image_url'
app/logical/downloads/file.rb:83:in `file_url'
app/logical/downloads/file.rb:15:in `uncached_url'
app/logical/downloads/file.rb:53:in `block in download!'
app/logical/downloads/file.rb:52:in `download!'
app/logical/upload_service/utils.rb:214:in `download_for_upload'
app/logical/upload_service/preprocessor.rb:97:in `start!'
app/logical/upload_service/preprocessor.rb:63:in `block in delayed_start'
app/logical/current_user.rb:10:in `scoped'
app/logical/current_user.rb:24:in `as'
app/logical/upload_service/preprocessor.rb:62:in `delayed_start'
```

**Comment by evazion** [comment]
The problem was this was a retweet and it failed because the tweet didn't contain any images.
