### ISSUE TITLE
Some artist histories throw exceptions

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3998]
Reported by Ars in the forums:

https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=37663
https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=19940

```ruby
ActionView::Template::Error exception raised
no implicit conversion of nil into Array

app/models/artist_version.rb:75:in `-'
app/models/artist_version.rb:75:in `other_names_diff'
app/helpers/artist_versions_helper.rb:3:in `artist_version_other_names_diff'
app/views/artist_versions/_revert_listing.html.erb:25:in `block in _app_views_artist_versions__revert_listing_html_erb__664043807317109978_69833992988500'
app/views/artist_versions/_revert_listing.html.erb:21:in `_app_views_artist_versions__revert_listing_html_erb__664043807317109978_69833992988500'
app/views/artist_versions/index.html.erb:6:in `_app_views_artist_versions_index_html_erb___4379393492975875045_69833993008340'
app/controllers/artist_versions_controller.rb:7:in `index'
```

**Comment by BrokenEagle** [comment]
This can be fixed either by programming around the **nil**, or by updating all of the artist versions with **nil** in the ``other_names`` field to be an empty array.  It would probably be better to just update all of the records, unless there would be some issue with updating the artist version records.

**Comment by evazion** [comment]
#3999 fixes the bad data.
